package service

import (
	"context"
	"testing"

	repomocks "github.com/Manan-AppPerfect/Backend/internal/common/repository/mocks"
	slackmocks "github.com/Manan-AppPerfect/Backend/internal/gateway/slack/mocks"
	usermocks "github.com/Manan-AppPerfect/Backend/internal/gateway/user/mocks"
	"github.com/golang/mock/gomock"
)

func TestTeamService(t *testing.T) {

	ctrl := gomock.NewController(t) // gomock controller: mock manager
	defer ctrl.Finish() // ensures all expected mock call happens

	mockRepo := repomocks.NewMockTeamRepository(ctrl)  // Creates a fake mockRepository generated by gomock
	mockUser := usermocks.NewMockGateway(ctrl) // fake mockUser
	mockSlack := slackmocks.NewMockGateway(ctrl) // fake mockSlack

	service := NewService(mockRepo, mockUser, mockSlack) // defined service

	mockUser.
		EXPECT().
		GetUser(gomock.Any(), int64(1)).
		Return("Kaizen", nil)

	mockRepo.
		EXPECT().  // when service calls repo, return this fake data using mockRepo.EXPECT()
		Create(gomock.Any(), gomock.Any()).  // called on the repository to return this fake team, gomock.Any() : any argument can be passed 
		Return(nil)

	mockSlack.
		EXPECT().
		SendMessage(gomock.Any(), gomock.Any()).
		Return(nil)

	result, err := service.CreateTeam(context.Background(), "Barcelona", 86, 654, 0) 

	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if result.Name != "Barcelona" {
		t.Fatalf("expected Barcelona, got %s", result.Name)
	}
}