openapi: 3.0.0
info: 
  title: Backend
  version: 1.0.0

paths: 
  /teams:
    post:
      summary: Create a team
      requestBody:
        required: true
        content: 
          application/json:
            schema: 
              $ref: '#/components/schemas/CreateTeamRequest'

      responses:
        '200':
          description: Team Created
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/Team'

  /teams/{id}:
    get:
      summary: Get team by id
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: integer

      responses:
        '200':
          description: Team found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Team'
  
  



components:
  schemas:
    CreateTeamRequest:
      type: object
      required:
        - id
        - name
        - age
        - playerCount
        - points
      properties:
        id:
          type: integer
        name:
          type: string
        age:
          type: integer
        playerCount:
          type: integer
        points: 
          type: integer

    Team:
      type: object
      properties: 
        id: 
          type: integer
        name: 
          type: string
        age: 
          type: integer
        playerCount:
          type: integer
        points:
          type: integer